In [1]:
import numpy as np

In [2]:
def test_run():
    print(np.array([2,3,4]))

In [3]:
if __name__=="__main__":
    test_run()

[2 3 4]


In [4]:
def test_run():
    #list of tuples in 2 D
    print(np.array([(2,3,4),(9,8,7)]))
test_run()

[[2 3 4]
 [9 8 7]]


In [5]:
def test_run():
    #Empty array
    print(np.empty(5))
    print(np.empty((5,4)))
test_run()

[  8.96335606e-309   5.82413632e-313   1.33360303e+241   1.49091424e-310
   3.27759114e-157]
[[  8.27591209e-312   6.27463370e-322   0.00000000e+000   0.00000000e+000]
 [  2.01589600e-312   5.30276956e+180   7.70748458e-043   4.57311440e-071]
 [  4.86450111e-086   3.35709097e-143   6.01433264e+175   6.93885958e+218]
 [  5.56218858e+180   3.94356143e+180   2.61004978e-057   1.69095583e-052]
 [  4.84882076e-033   7.55926329e-067   8.07238931e-144   1.50008929e+248]]


In [6]:
def test_run():
    #Array of ones
    print(np.ones((5,4)))
test_run()

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [7]:
def test_run():
    #list of tuples in 2 D
    print(np.random.random((5,4)))
test_run()

[[ 0.18493828  0.11420377  0.54522799  0.33650963]
 [ 0.52822834  0.61334241  0.25340534  0.68799706]
 [ 0.40815539  0.99293697  0.52605427  0.79148284]
 [ 0.67899676  0.79294449  0.77455505  0.84756941]
 [ 0.30466666  0.03239581  0.13886134  0.90463448]]


In [8]:
def test_run():
    #list of tuples in 2 D
    print(np.random.rand(5,4))
test_run()

[[ 0.76167898  0.85029824  0.66546051  0.24323673]
 [ 0.37988787  0.92964506  0.68662909  0.81456172]
 [ 0.74327611  0.80521053  0.70879185  0.00112571]
 [ 0.26133443  0.74757874  0.86666451  0.31712833]
 [ 0.44049015  0.9726568   0.98954023  0.78635947]]


In [9]:
def test_run():
    #sample from normal(gaussian) function
    print(np.random.normal(size=(5,4)))
test_run()

[[ 1.06623776  0.28316963 -0.0210116  -1.39117644]
 [ 1.00634574  0.22549934  1.40300176  0.92513715]
 [-1.1495291  -1.83614919 -0.30850328 -0.88050182]
 [-1.2477992  -0.46505062 -0.21112972 -0.02312118]
 [ 2.97916573  0.44377426  0.93030136  0.52153423]]


In [10]:
def test_run():
    #sample from normal(gaussian) distribution
    print(np.random.normal(50,10,size=(2,3)))
test_run()

[[ 57.10549028  42.23786512  44.91594173]
 [ 50.0704617   40.69065166  51.27054589]]


In [11]:
def test_run():
    #sample from normal(gaussian) function
    a=np.random.random((5,4))
    print(a.shape)
test_run()

(5, 4)


In [12]:
def test_run():
    #sample from normal(gaussian) function
    a=np.random.random((5,4))
    print(a.shape[0]) #number of Rows
    print(a.shape[1]) #number of Columns
test_run()

5
4


In [13]:
def test_run():
    #sample from normal(gaussian) function
    a=np.random.random((5,4))
    print(a.size) #number of Rows
   
test_run()

20


In [14]:
def test_run():
    #sample from normal(gaussian) function
    a=np.random.random((5,4))
    print(a.dtype) #number of Rows
test_run()

float64


In [17]:
def test_run():
    #sample from normal(gaussian) function
    np.random.seed(693)# seed the random number generator
    a=np.random.randint(0,10,size=(5,4)) #5*4 random nteger in [0,10]
    print("Array\n",a) #number of Rows
test_run()

Array
 [[2 0 5 1]
 [1 3 4 4]
 [9 2 9 1]
 [9 3 7 5]
 [4 7 0 3]]
